# Generated by Django 2.2.1 on 2019-06-04 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': '职位',
                'db_table': 'positioninfo',
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project_models.PositionInfo'),
        ),
    ]
