# Generated by Django 2.2.1 on 2019-06-04 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_models', '0002_auto_20190604_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineGroupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machinegroup', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': '主机组',
                'db_table': 'machinegroupinfo',
            },
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=20, unique=True)),
                ('host', models.CharField(max_length=15, unique=True)),
                ('port', models.IntegerField(default=2376, max_length=5)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_models.MachineGroupInfo')),
            ],
            options={
                'verbose_name_plural': '主机',
                'db_table': 'hosts',
            },
        ),
    ]
