# Generated by Django 2.2.1 on 2019-06-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('project_models', '0003_hostinfo_machinegroupinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='port',
            field=models.IntegerField(default=2376),
        ),
    ]
